source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg', '~> 0.11'
gem 'sqlite3', '~> 1.3.5'
gem 'ar-octopus', '0.6.0'
gem 'pry'
gem 'json', '~> 1.8.6'

group :test do
  gem 'capybara'
  gem 'cucumber-rails', :require => false
  gem 'launchy'
  gem 'rspec-rails'
  gem 'aruba'
  gem 'database_cleaner'
end
